### ISSUE TITLE
TMC2660 sensorless homing compile error

### ISSUE THREAD

**Issue by stefan85** [teemuatlut/Marlin#28]
Hi,

I started to use your fork for testing my new board with a lpc1769 processor with TMC2660 drivers.
At the moment compiling with sensorless homing disabled is working.

When I enable sensorless homing i get this message:

`Marlin\src\lcd\ultralcd.cpp:1784:79: error: invalid conversion from 'int8_t* {aka signed char*}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
#define TMC_EDIT_STORED_SGT(ST) MENU_ITEM_EDIT_CALLBACK(int8, MSG_##ST, &stepper##ST.stored.homing_thrs, -64, 63, refresh_tmc_homing_thrs);`

Do you have this issue also?

**Comment by teemuatlut** [comment]
Sensorless homing with `TMC2660` is not implemented yet.
If you just need to try TMC2660, then I'd suggest sticking with the upstream code.

Nonetheless, thank you for letting me know about the compile issues. Looks like I need to broaden my test cases a bit.
