### ISSUE TITLE
TMCStepper_REGDEFS.h: No such file or directory

### ISSUE THREAD

**Issue by 00alkskodi00** [teemuatlut/Marlin#29]
Hi i have this error : TMCStepper_REGDEFS.h: No such file or directory

**Comment by teemuatlut** [comment]
There's no file that is named like that and there's also no include that would attempt to use a file named as such.
What branch are you trying to compile?

**Comment by 00alkskodi00** [comment]
Oh 

sorry i have downloaded Marlin-trams-updated.zip is this zip file from you ?

**Comment by 00alkskodi00** [comment]
i loking marlin for trinamic, i have oficial marlin for trinamic downloaded but i need connect lcd12864 and that my make problems :D

**Comment by teemuatlut** [comment]
What drivers are you trying to use?

**Comment by 00alkskodi00** [comment]
i have trams shield whit TMC5130 on arduino mega

**Comment by teemuatlut** [comment]
Then this is the only firmware that's working for you
https://github.com/trinamic/TRAMS-Firmware
until I can finish bringing the support upstream. I won't be making any promises on a timeline for that.

**Comment by 00alkskodi00** [comment]
thank you very much, i must now buy DUET WIFI :D
